/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mockExam;

import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        LinkedList<Integer> linkedList = new LinkedList();
        linkedList.addData(15);
        linkedList.addData(5);
        linkedList.addData(25);
        linkedList.addData(45);
        linkedList.addData(35);
        linkedList.addData(68);
        linkedList.addData(60);
        linkedList.addData(55);
        linkedList.maxValue();
        linkedList.minValue();
        linkedList.secondMaxValue();
        linkedList.midValue();

        LinkedList<Integer> linkedList1 = new LinkedList();
        linkedList1.addData(100);
        linkedList1.addData(82);
        linkedList1.addData(122);
        linkedList1.addData(70);
        linkedList1.addData(0);
        linkedList1.addData(50);
        linkedList1.addData(13);
        linkedList1.maxValue();
        linkedList1.minValue();
        linkedList1.secondMaxValue();
        linkedList1.midValue();

        LinkedList<Integer> l3 = new LinkedList<>();
        l3.mergeLinkedList(linkedList1, linkedList);

        LinkedList<Integer> l4 = new LinkedList<>();
        l4.appendValue(3);
        l4.appendValue(4);
        l4.appendValue(5);
        l4.appendValue(4);
        l4.appendValue(3);
        System.out.println(l4.palindrome(l4));

        linkedList1.revers(linkedList1);

    }
}
